#!/bin/sh
# git-backup should be in root of WordPress and calls:
# wp-content/plugins/jeffpack-multi-git/git-backup-all.sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"$DIR/wp-content/plugins/jeffpack-git/git-backup-all.sh" "$@"