#!/bin/bash

phpdoc_cmd () {
	local wd="$(pwd)"
	local this_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	local phpdoc_repo="$this_dir/phpDocumentor2"
	
	local templates_dir="$phpdoc_repo/data/templates"
	local phpdoc_exec="$phpdoc_repo/bin/phpdoc"

	mkdir -p "$wd/$1/phpdoc"
	"$phpdoc_exec" -d "$wd/$1" -t "$wd/$1/phpdoc" --template="clean"
	# "$phpdoc_exec" -d "$wd/$1" -t "$wd/$1/phpdoc" --template="old-ocean"
	# "$phpdoc_exec" -d "$wd/$1" -t "$wd/$1/phpdoc" --template="responsive"
	# "$phpdoc_exec" -d "$wd/$1" -t "$wd/$1/phpdoc" --template="zend"
	# "$phpdoc_exec" -d "$wd/$1" -t "$wd/$1/phpdoc" --template="checkstyle"
}
phpdoc_cmd "$1"

