#!/bin/bash

validate_json_cmd () {
	local wd="$(pwd)"
	local this_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	local phpdoc_repo="$this_dir/phpDocumentor2"

	local validate_json_exec="$phpdoc_repo/bin/validate-json"

	"$validate_json_exec" "$@"
}
validate_json_cmd "$@"
